M48
; DRILL file {KiCad (6.0.0)} date Sat Aug 27 02:03:38 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-27T02:03:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0701
%
G90
G05
T1
X4.81Y-2.3096
X4.81Y-2.9096
X6.41Y-2.3096
X6.41Y-2.9096
T0
M30
